src/index.ts

I think this is probably fine. We'll only ever be exporting components otherwise which will be PascalCase anyway.

feat(tokens): exposes tokens through om

---

.storybook/decorators/globalStyles.scss
.storybook/decorators/globalStyles.ts
src/components/Breakpoint/Breakpoint.tsx
src/components/Button/Button.scss
src/components/Clickable/Clickable.scss
src/index.scss
src/mixins/global-styles/_global-styles.scss

- removes global-styles invocation when importing library
- includes margin reset for buttons (Safari has a 2px margin on all buttons)
- fixes initial mount/unmount of Breakpoint

Fix for Breakpoint mounting; refactor SCSS library initialization

---

src/components/Input/Input.scss
src/components/Input/Input.stories.tsx
src/components/Input/Input.test.tsx
src/components/Input/Input.tsx

This seemed like the easiest API to add here, but I am open to ideas on better setups. I basically don't want to have to manually wrap labels and inputs all over the app.

feat(input): add optional label to input

---

package.json
scripts/scaffold/react.js
src/components/AspectRatioBox/AspectRatioBox.stories.tsx
src/components/Badge/Badge.stories.tsx
src/components/Breadcrumbs/Breadcrumbs.stories.tsx
src/components/Button/Button.stories.tsx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Clickable/Clickable.stories.tsx
src/components/ColorSwatch/ColorSwatch.stories.tsx
src/components/DefinitionList/DefinitionList.stories.tsx
src/components/Divider/Divider.stories.tsx
src/components/Expandable/Expandable.stories.tsx
src/components/Field/Field.stories.tsx
src/components/Label/Label.stories.tsx
src/components/Loading/Loading.stories.tsx
src/components/Popover/Popover.stories.tsx
src/components/PromoBanner/PromoBanner.stories.tsx
src/components/RadioButton/RadioButton.stories.tsx
src/components/SearchInput/SearchInput.stories.tsx
src/components/Select/Select.stories.tsx
src/components/SelectableButton/SelectableButton.stories.tsx
src/components/Stack/Stack.stories.tsx
src/components/Tabs/Tab.scss
src/components/Tabs/Tabs.stories.tsx
src/components/Text/Text.stories.tsx
src/components/Text/Text.tsx
src/components/TextInput/TextInput.stories.tsx
src/components/Textarea/Textarea.stories.tsx
yarn.lock

I wound up extracting the states component into it's [own package](https://github.com/dzucconi/storybook-states) — fixed some bugs and made it typesafe. This converts the stories to use it. I'll convert the stories in discovery then kill it in this package.

chore: converts to using storybook-states

---

src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx

Make the `Checkbox` component update when the `checked` property is changed.
See https://github.com/ModaOperandi/discovery/pull/633#discussion_r395190643 where @jmcriffey had to force rerender the components in order to get the checkboxes updated.

fix(checkbox): checked/defaultChecked behavior

---

src/components/Select/Select.tsx
src/components/Select/SelectOptions.tsx

Oops, I forgot the keyboard navigation here.

fix(select): skip disabled options on keyboard navigation

---

src/components/Select/Select.tsx

Started off debugging the modal and landed on this; was intercepting `esc`, globally if it was on a specific page.

fix(select): avoids clobbering the global esc key handler

---

src/components/Popover/Popover.scss
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.tsx

`anchor` can now be 'topLeft', 'topCenter', 'topRight', 'bottomLeft', 'bottomCenter', 'bottomRight'.
e.g. 'bottomCenter':
BREAKING CHANGE: anchor: 'left' is now anchor: 'topLeft' and anchor: 'right' is anchor: 'topRight'

feat(popover): add more positioning options

---

src/components/Popover/Popover.scss
yarn.lock

While working with Popovers I realized that the offset is too small, see this example:
Before:
After:
I added padding to some elements to 'fix' this, so after this is merged, I'll need to remove those paddings too in discovery.

fix(popover): increase offset

---

package.json
src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
webpack.config.js
yarn.lock

A button can have a `href` attribute but it will always do a full page reload when clicked. This
makes it possible to pass in a `to` attribute which will make it a react-router link.
BREAKING CHANGE: react-router-dom is a peerDepencency now. All packages using om will have to
install react-router-dom too.

feat(button): render as a react-router link

---

src/components/Modal/Modal.scss
src/components/RadioButton/RadioButton.scss

Add some padding to ModalOverlay.
Remove the small margin from RadioButton and center the contents vertically.

fix: modal and radiobutton styles

---

src/components/Select/Select.scss

Make the height of `Select` match `TextInput`.

fix(select): make height match input

---

src/components/Select/SelectOption.tsx

The dropdown does not close when selecting an item when the `Select` component is in a `Field`.

fix(select): dropdown does not close when in Field

---

src/components/RadioButton/RadioButton.scss

`RadioButton` should always have a white background, otherwise it looks weird on non-white backgrounds:

fix(radiobutton): make bgcolor white

---

src/components/Clickable/Clickable.scss

I don't think that we're wrapping anything that's clickable and if so, we can overwrite the prop when specially needed.

fix(<clickable />): fix wrapping

---

src/components/Breadcrumbs/Breadcrumbs.tsx

null creadcrumb fix
We want to make sure that the child passed to the Bradcrumbs component is not null, otherwise it
will render the separator("/") without any text.

fix(breadcrumbs): null child

---

src/components/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
src/components/Breadcrumbs/Breadcrumbs.stories.tsx
src/components/Breadcrumbs/Breadcrumbs.test.tsx
src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Breadcrumbs/index.ts

Adds `<meta itemprop="position" />`, `itemprop="item"` to the anchors and `itemprop="name"` to the
names.
BREAKING CHANGE: The props api have changed, now you need to explicitly render `<Breadcrumb>`
components inside of `<Breadcrumbs>`.
DOOR-120

feat(breadcrumbs): microdata improvements

---

src/components/Clickable/Clickable.scss
src/components/Clickable/Clickable.tsx
src/components/Select/Select.scss

Now in select boxes the arrow on the right is clickable as well. also the label inside
buttons/clickables will have the same curser behavior as the parent

fix(select and clickable): allow arrow click and label pointer view

---

src/components/Select/Select.scss
src/mixins/input-styles/_input-styles.scss

if inputs are font-size < 16px, ios devices automatically zoom the user in and won't zoom out

fix(inputs and selects): ios devices need font size 16

---

src/components/Button/Button.scss

we have accessibility issues on disabled buttons, so we make the color darker

fix(disabled button)

---

src/components/Button/Button.scss

Button focus styling was confused with the disabled state, and also updated them to reflect the buttons from the core library: https://www.figma.com/file/FrC7k1AZjKH07OhiDYhBpM/Om-Core-Library?node-id=1417%3A0
Primary before:
Primary after:
Secondry before:
Secondry after:
DOOR-504

fix(button.scss): button focus style

---

package.json
src/components/Select/SelectOption.tsx
src/components/Select/SelectOptions.tsx
src/hooks/index.ts
src/hooks/useKeyboardListNavigation.spec.ts
src/hooks/useKeyboardListNavigation.ts
yarn.lock

Allow searching by keywords and scroll active element into view.
Also copied [use-keyboard-list-navigation](https://github.com/dzucconi/use-keyboard-list-navigation) into the repo because I don't have push access to that repo.

feat(select): improve keyboard navigation

---

src/components/Modal/Modal.tsx
src/components/ModalOverlay/ModalOverlay.tsx

Allow passing in `shards` in props to allow interacting with things like recaptcha while the modal is open.
See [react-focus-on](https://github.com/theKashey/react-focus-on#focuson).

feat(modal): add shards to props

---

src/components/Overlay/Overlay.scss

Fixes the flickering effect after the overlay is hidden:

fix(overlay): animation

---

src/components/Badge/Badge.tsx

badges dont need to be clickable. Reverting to what it used to be before

feat(badge): removed clickable

---

src/components/Badge/Badge.test.tsx
src/components/Badge/Badge.tsx

we don't always want the badge to be a link, we don't use it as that at all (for the moment) and we can wrap it within a <a/> when it's needed;
but, that being used so, created this:

fix(badge): make badge a span and not a link

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.tsx
src/components/RadioButton/RadioButton.scss
src/components/RadioButton/RadioButton.stories.tsx
src/components/RadioButton/RadioButton.tsx

Disabled checkbox style looked the same as the enabled one
Before:
After:

feat(checkbox): disabled checkbox style

---

src/components/Breadcrumbs/Breadcrumb/Breadcrumb.scss

Make mobile Breadcrumbs look like the desktop ones
Mobile:
ECOM-793

feat(breadcrumb): same link divider on mobile as on desktop

---

src/components/Field/Field.tsx
src/components/SearchInput/SearchInput.tsx
src/components/TextInput/TextInput.tsx
src/components/Textarea/Textarea.tsx

Make the onChange type consistent across Input, Textarea and Select.
BREAKING CHANGE: The argument of onChange is the new value instead of the change event in Input and
Textarea

fix(input): onChange type

---

src/components/Popover/Popover.scss
src/components/Popover/Popover.tsx

1 is usually a good z-index for the popover content, however in some cases (e.g. in modals) we need a larger z-index.
We can overwrite it from scss but that's not always the cleanest solution, it's a good alternative to pass in the `zIndex` in props.

feat(popover): make zIndex configurable

---

src/components/Select/Select.tsx

Adds `autoSelect` to props.
If it's `true`, selecting a value will update the selection automatically, even if the `value` passed from `props` doesn't change.
If it's `false`, selecting a value will not update the selection, the user has to make sure the `value` is appropriately updated on `onChange`.
If no `value` is passed in from props, the component will be _uncontrolled_, meaning that it will keep it's internal state and update it accordingly when selecting a value.
Note: We can usually use the default `autoSelect: true` option. However, there are cases when the user is required to confirm the change. One example is switching rule versions in facade when the current draft is dirty.

feat(Select): autoSelect

---

src/components/Expandable/Expandable.tsx

Allow the component to be controlled with the `expanded` property.
For uncontrolled usages, use `defaultExpanded`.
For more info on what's the difference between controlled and uncontrolled see https://reactjs.org/docs/uncontrolled-components.html
ISSUES WORKED ON: ECOM-2127
BREAKING CHANGE: 'expanded' will now control the component completely

feat(expandable): allow it to be controlled

---

src/components/Expandable/Expandable.scss
src/components/Expandable/Expandable.stories.tsx
src/components/Expandable/Expandable.tsx

feat(expandable): dark background

---

src/components/SearchInput/SearchInput.stories.tsx
src/components/SearchInput/SearchInput.test.tsx
src/components/SearchInput/SearchInput.tsx

Removes the 'onChangeValue' callback, 'onChange' can be used instead.
Also removes the `useEffect` that called `onChangeValue`.
Not confirmed, but this can be the source of a UI glitch that happens on the search bar intermittently.
ISSUES WORKED ON: ECOM-2215
BREAKING CHANGE: removed 'onChangeValue'

fix(searchinput): clean up props

---

src/components/Tabs/Tabs.tsx

Allows controlling the selected tab by the user of the component.
BREAKING CHANGE: `activeTab` now controls the component, for uncontrolled behavior, use `defaultActiveTab` instead.

feat(tabs): allow controlling the selected tab

---

src/components/SearchInput/SearchInput.scss
src/components/SearchInput/SearchInput.stories.tsx
src/components/SearchInput/SearchInput.tsx

new Global header refresh suggests that we remove the border on SearchInput. 
Adding that as a prop here.

feat(search): add noBorders prop
