enzyme.config.js
jest.config.js
package.json
scripts/scaffold.js
src/components/Button/Button.test.tsx
tsconfig.json
yarn.lock

Closes #4
We can add snapshots too but I'd like to see how far we get with just more targeted specs.

test(jest): sets up jest

---

src/components/Stack/Stack.scss
src/components/Stack/Stack.stories.tsx
src/components/Stack/Stack.test.tsx
src/components/Stack/Stack.tsx
src/components/Stack/index.ts
src/components/Text/Text.scss
src/components/Text/Text.stories.tsx
src/components/Text/Text.test.tsx
src/components/Text/Text.tsx
src/components/Text/index.ts
src/index.ts

Not much here; I just wanted to initialize a TopNav component inside of portal and want to just include something from this so that I can validate the entire stack of packages is working.

Stack & Text

---

documentation/src/App.scss
documentation/src/components/Sidebar/Sidebar.scss
documentation/yarn.lock

finishes migration to @moda/tokens 2.1.0
BREAKING CHANGE: See https://github.com/ModaOperandi/tokens/releases/tag/v2.0.0 and
https://github.com/ModaOperandi/tokens/releases/tag/v2.1.0 for details

feat(tokens): completes @moda/tokens upgrade

---

src/components/Expandable/Expandable.scss
src/components/Expandable/Expandable.stories.tsx
src/components/Expandable/Expandable.test.tsx
src/components/Expandable/Expandable.tsx
src/components/Expandable/index.ts
src/components/index.ts

Quick `Expandable` needed for PDP sidebar as well as SiteFooter

feat(components): implements Expandable

---

.gitignore
documentation/src/App.scss
package.json
src/molecules/Divider/Divider.scss
src/molecules/Divider/Divider.stories.tsx
src/molecules/Divider/Divider.test.tsx
src/molecules/Divider/Divider.tsx
src/molecules/Divider/index.ts
src/molecules/NavBar/NavBarPulldownSubsection.scss
src/molecules/SiteNav/SiteNav.scss
src/molecules/SiteNav/SiteNav.stories.tsx
src/molecules/SiteNav/SiteNav.tsx
src/molecules/SiteNav/index.ts
src/molecules/TopNav/index.ts
src/molecules/index.ts
src/utilities/States/States.tsx
yarn.lock

Additionally renaming TopNav => SiteNav

Upgrades to @moda/tokens 3.0.0

---

src/components/PromoBanner/PromoBanner.scss
src/components/PromoBanner/PromoBanner.stories.tsx
src/components/PromoBanner/PromoBanner.test.tsx
src/components/PromoBanner/PromoBanner.tsx
src/components/PromoBanner/index.ts
src/components/index.ts

feat(components): implements PromoBanner

---

package.json
src/components/Modal/Modal.test.tsx
src/components/Modal/Modal.tsx
yarn.lock

Clicking anywhere inside the modal closes it right now, so we need to make sure to only close when the background is clicked.

fix(modal): onClose only when wrapper is clicked

---

.vscode/settings.json
src/components/Input/Input.tsx
src/components/Modal/Modal.test.tsx
src/components/SearchInput/SearchInput.scss
src/components/SearchInput/SearchInput.stories.tsx
src/components/SearchInput/SearchInput.test.tsx
src/components/SearchInput/SearchInput.tsx
src/components/SearchInput/index.ts
src/components/index.ts

SearchInput

---

src/components/Input/Input.scss
src/components/Modal/Modal.tsx
src/components/Textarea/Textarea.scss
src/components/Textarea/Textarea.stories.tsx
src/components/Textarea/Textarea.test.tsx
src/components/Textarea/Textarea.tsx
src/components/Textarea/index.ts
src/mixins/_mixins.scss
src/mixins/components/input-styles.scss

@dzucconi feel free to look at this when you get back, i imagine you might have some thoughts, i basically just copied the input component and changed to text area.

feat(textarea): add textarea component and input styles mixin

---

src/components/ColorSwatch/ColorSwatch.stories.tsx
src/components/ColorSwatch/ColorSwatch.tsx

fix(swatch): hover -> mouseover mouseout

---

src/index.ts
src/utilities/States/States.tsx
src/utilities/index.ts

I think I might pull this out into it's own package as it's more broadly useful. Exporting under the `Utilities` namespace for the time being.

feat(utilities): exports Utilities namespaced States component

---

src/components/Badge/Badge.tsx
src/components/index.ts

fix(badges): update themeing of badges

---

package.json
yarn.lock

Need to look into dependabot support for pinning versions.

feat: specifies correct version

---

src/components/PromoBanner/PromoBanner.scss
src/mixins/_mixins.scss
src/mixins/thin-underline/_thin-underline.scss
src/mixins/thin-underline/thin-underline.stories.scss
src/mixins/thin-underline/thin-underline.stories.tsx

Updates PromoBanner colors

---

package.json
src/components/AspectRatioBox/AspectRatioBox.scss
src/components/AspectRatioBox/AspectRatioBox.stories.tsx
src/components/AspectRatioBox/AspectRatioBox.test.tsx
src/components/AspectRatioBox/AspectRatioBox.tsx
src/components/AspectRatioBox/index.ts
src/components/index.ts
yarn.lock

feat(components): implements aspect ratio box

---

src/components/Tabs/Tab.scss
src/components/Tabs/Tab.tsx
src/components/Tabs/TabList.scss
src/components/Tabs/TabList.tsx
src/components/Tabs/TabPanel.tsx
src/components/Tabs/TabPanels.scss
src/components/Tabs/TabPanels.tsx
src/components/Tabs/Tabs.stories.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/index.ts
src/components/index.ts

Add all components required for Tabs feature
re OM-27

feat(tabs): Create Tabs feature

---

src/components/ColorSwatch/ColorSwatch.scss
src/components/ColorSwatch/ColorSwatch.stories.tsx
src/components/ColorSwatch/ColorSwatch.test.tsx
src/components/ColorSwatch/ColorSwatch.tsx

feat(swatches): further refines color swatches

---

.storybook/config.js
package.json
src/components/Button/Button.scss
src/components/Checkbox/Checkbox.tsx
src/components/ColorSwatch/ColorSwatch.scss
src/components/Expandable/Expandable.scss
src/components/Expandable/Expandable.stories.tsx
src/components/RadioButton/RadioButton.test.tsx
src/components/RadioButton/RadioButton.tsx
src/components/Select/Select.scss
src/components/SelectableButton/SelectableButton.scss
src/index.ts
src/mixins/global-styles/_global-styles.scss
yarn.lock

Polyfills focus-visible. This should enable focus rings inside of consumers of om.

[a11y] :focus-visible

---

package.json
src/components/Loading/Loading.tsx
yarn.lock

While I'm debugging issues with hydration, I'm thinking that the random initial state of the loading indicator might be causing the DOM mismatch — theoretically it shouldn't, but I'm not 100% here. We're set to redo this soon in any event.

fix(loading): makes loading indicator deterministic

---

package.json
src/components/Select/Select.scss
src/components/Select/Select.stories.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
src/components/Select/SelectOption.scss
src/components/Select/SelectOption.tsx
yarn.lock

feat(select): disabled & disabled option

---

src/components/Select/Select.test.tsx
src/components/Select/Select.tsx

the select was ignored by the form component

fix: 🐛 fix select within <form />

---

prettier.config.js

This repo doesn't use any @moda repos, should we set it up to do so?

chore(prettier): update config to match 1.x defaults

---

src/components/Select/Select.tsx
yarn.lock

state gets updated when receiving props so, by the effect, props.onChange would trigger and so on..

fix: 🐛 fix <Select /> callback

---

src/mixins/input-styles/_input-styles.scss

fix(textinput): update form field error state to full 1px red border

---

src/components/SearchInput/SearchInput.stories.tsx

This change allows the search input to be controlled via prop

fix(search input): releasing a beautiful change to the search input

---

src/components/Stack/Stack.stories.tsx
src/components/Stack/Stack.tsx

as the ticket description says, there are plenty of classes assigned to items that are just changing those two properties

feat(<stack />): added justifyContent and alignItems props

---

src/components/Badge/Badge.scss

some updates from figma. Double checked about padding w/Rebecca as well.

feat(badge): updates colors & padding

---

src/components/Expandable/Expandable.scss
src/components/Expandable/Expandable.stories.tsx

fix(expandable): handle overflowing text

---

src/components/Tag/Tag.scss
src/components/Tag/Tag.stories.tsx
src/components/Tag/Tag.test.tsx
src/components/Tag/Tag.tsx
src/components/Tag/index.ts
src/components/index.ts

feat(tag): add component

---

src/components/Breakpoint/Breakpoint.tsx
src/hooks/index.ts
src/hooks/useBreakpoint.ts

Added a new hook called useBreakpoint

feat: add breakpoint hook

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
src/components/Select/SelectLabel.tsx

We must display a ":" between label and value in case value is not undefined

fix(fix select label):

---

src/components/Popover/Popover.scss
src/components/Popover/Popover.stories.tsx

this enables links to work properly if we want to use them inside a popover

feat(popover): fixes caret

---

src/components/Toast/Toast.scss
src/components/Toast/Toast.stories.tsx
src/components/Toast/Toast.test.tsx
src/components/Toast/Toast.tsx
src/components/Toast/index.ts
src/components/index.ts

feat: adds toast

---

.releaserc
package.json
yarn.lock

Use https://github.com/jedmao/semantic-release-npm-github-config mainly to keep the version in _package.json_ in sync.
This shouldn't be marked as a `feat` but I want to see this in action to make sure it works correctly 😄

feat(tools): use semantic-release-npm-github-config

---

src/components/Field/Field.stories.tsx
src/components/Field/Field.test.tsx
src/components/Field/Field.tsx
src/components/Select/Select.scss
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

On dropdowns the error icon is overlaping the caret

fix(component): fix error on dropdowns

---

src/components/Badge/Badge.scss
src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx

not a big issue but pretty weird to use `fall-25` theme on `treat30`

feat(badges): renamed badge theme 'fall-25' to be more generic

---

src/components/Expandable/Expandable.stories.tsx
src/components/Expandable/Expandable.tsx

Adding virtual prop to expandable component in order to load the child of the expandable component
into the DOM only after is expanded
ECOM-714

feat(expandable comp): adding virtual prop to expandable component

---

src/components/Select/Select.scss
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

adding autofill feature to select component

feat(select component): adding autofill feature to select component

---

src/components/Constrain/ExceedConstrain.scss
src/components/Constrain/ExceedConstrain.stories.tsx
src/components/Constrain/ExceedConstrain.tsx
src/components/Constrain/index.ts

Add an ExceedConstrain component to allow exceeding the constrain.

feat(constrain): exceed constrain

---

src/components/Popover/Popover.scss
src/components/Popover/Popover.stories.tsx
src/components/Popover/Popover.tsx

https://user-images.githubusercontent.com/43396056/145593649-6d026725-e181-4467-9ca4-44a906257ce0.mov

feat(popover): adds popover smooth animation

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

https://user-images.githubusercontent.com/43396056/174073120-e2e27ae4-016f-4280-a49e-fa869a684404.mov

feat(select): adds placeholder as prop and places it within its label

---

src/components/ColorSwatch/skuColors.ts

feat(colorswatch): add new colors

---

src/components/Badge/Badge.scss
src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx

feat(badge): adds noise theme

---

.eslintrc.js
.github/workflows/auto-merge.yml
src/components/Breakpoint/Breakpoint.tsx
src/components/LoadingBalls/LoadingBalls.tsx

feat(breakpoint): allow passing in html attributes

---

src/components/Modal/Modal.tsx

feat(modal): make autoFocus optional

---

src/components/Checkbox/Checkbox.tsx
src/components/Select/Select.tsx
src/components/Select/SelectOptions.tsx
src/components/SlidingPane/SlidingPane.scss
src/components/SlidingPane/SlidingPane.tsx
src/components/Text/Text.tsx

feat: accessibility improvements

---

src/components/Expandable/Expandable.stories.tsx

forgot this needs to be a `feat` to have a new version

feat(version): release tokens version

---

src/components/SearchInput/SearchInput.scss
src/components/SearchInput/SearchInput.stories.tsx
src/components/SearchInput/SearchInput.tsx

feat(searchinput): adds round borders prop/option

---

src/components/PromoBanner/PromoBanner.scss

This should make it easier to set text color on the Promo Banner (we've been changing it often lately)

feat(promo banner): default color

---

src/components/Select/Select.scss
src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

🍓 
this is a demo implementation, an UI/UX work for designers' approval

fix(select): adds a color swatch whenever a color is provided

---

src/components/Select/Select.scss
src/components/Select/Select.stories.tsx

fix(select): fixes color swatch props
